import React, { Suspense, lazy, useMemo, useState } from 'react'

const Plot = lazy(() => import('react-plotly.js'))

const PALETTE = ['#00e5ff', '#00ff9d', '#ffb300', '#e040fb', '#ff4d6a', '#7986cb']

const BASE_LAYOUT = {
  autosize:      true,
  paper_bgcolor: 'rgba(0,0,0,0)',
  plot_bgcolor:  'rgba(0,0,0,0)',
  font:          { family: '"JetBrains Mono", monospace', color: '#e8eaf6', size: 11 },
  colorway:      PALETTE,
  margin:        { t: 32, r: 20, b: 52, l: 56 },
  xaxis: {
    gridcolor: '#1e2235', zerolinecolor: '#2d3555', linecolor: '#2d3555',
    tickfont: { color: '#7986cb', size: 10 },
  },
  yaxis: {
    gridcolor: '#1e2235', zerolinecolor: '#2d3555', linecolor: '#2d3555',
    tickfont: { color: '#7986cb', size: 10 },
  },
  legend: {
    bgcolor: 'rgba(20,23,32,0.85)', bordercolor: '#1e2235', borderwidth: 1,
    font: { color: '#e8eaf6', size: 10 },
  },
}

const BASE_CONFIG = {
  displaylogo: false,
  responsive: true,
  modeBarButtonsToRemove: ['select2d', 'lasso2d', 'autoScale2d'],
  toImageButtonOptions: { format: 'png', scale: 2, filename: 'insightagent-chart' },
}

const CHART_ICONS = { bar: '▦', line: '∿', pie: '◕', scatter: '⁙', area: '◿', histogram: '▬' }

/**
 * ChartRenderer
 * -------------
 * Dual-mode chart display:
 *
 *  MODE A — "image"    : shows the chart.png generated by the backend (matplotlib)
 *  MODE B — "plotly"   : builds an interactive Plotly chart from the row data
 *
 * The user can toggle between both modes when both are available.
 *
 * Props:
 *   chartUrl   {string}    Full URL to backend chart image  (from AskAIResponse.chartUrl)
 *   data       {Object[]}  Row data array                   (from AskAIResponse.data)
 *   columns    {string[]}  Column names
 *   chartType  {string}    "bar" | "line" | "pie" | "scatter" | "area"
 *   isLoading  {boolean}
 *   height     {number}    px (default 300)
 */
export default function ChartRenderer({
  chartUrl  = null,
  data      = [],
  columns   = [],
  chartType = 'bar',
  isLoading = false,
  height    = 300,
}) {
  // Default to image view when backend chart is available; else plotly
  const [mode, setMode] = useState(chartUrl ? 'image' : 'plotly')
  const hasBoth = !!chartUrl && data.length > 0

  // Switch to image mode when a new chartUrl arrives
  React.useEffect(() => {
    if (chartUrl) setMode('image')
  }, [chartUrl])

  const { traces, layout } = useMemo(
    () => buildFigure(data, columns, chartType, height),
    [data, columns, chartType, height],
  )

  const icon = CHART_ICONS[chartType] ?? '◈'

  return (
    <div className="flex flex-col rounded-xl border border-panel-border bg-surface-50 overflow-hidden animate-fade-in">

      {/* Header */}
      <div className="flex items-center gap-2 px-4 py-2.5 bg-surface-100 border-b border-panel-border shrink-0">
        <span className="text-accent-cyan text-sm">{icon}</span>
        <span className="label-mono text-accent-cyan">
          {chartType ? `${chartType} chart` : 'chart'}
        </span>
        {data.length > 0 && (
          <span className="ml-2 label-mono text-text-muted">{data.length} rows</span>
        )}

        {/* Mode toggle — only when both are available */}
        {hasBoth && (
          <div className="ml-auto flex items-center gap-1 bg-surface-200 rounded-lg p-0.5">
            <ModeBtn label="image"   active={mode === 'image'}  onClick={() => setMode('image')}  />
            <ModeBtn label="plotly"  active={mode === 'plotly'} onClick={() => setMode('plotly')} />
          </div>
        )}
        {!hasBoth && (chartUrl || data.length > 0) && (
          <span className="ml-auto label-mono text-text-muted text-[10px]">
            {chartUrl ? 'backend chart' : 'interactive'}
          </span>
        )}
      </div>

      {/* Chart body */}
      <div style={{ minHeight: `${height}px` }} className="flex items-center justify-center">
        {isLoading ? (
          <Skeleton height={height} />
        ) : mode === 'image' && chartUrl ? (
          <ImageChart url={chartUrl} height={height} />
        ) : traces.length > 0 ? (
          <Suspense fallback={<Skeleton height={height} />}>
            <Plot
              data={traces}
              layout={layout}
              config={BASE_CONFIG}
              style={{ width: '100%', height: `${height}px` }}
              useResizeHandler
            />
          </Suspense>
        ) : (
          <EmptyChart height={height} icon={icon} />
        )}
      </div>
    </div>
  )
}

// ─── Image chart ──────────────────────────────────────────────────────────────

function ImageChart({ url, height }) {
  const [imgError, setImgError] = useState(false)
  // Add cache-bust so a fresh query always reloads the image
  const bustedUrl = `http://localhost:8000${url}?t=${Date.now()}`

  if (imgError) {
    return (
      <div className="flex flex-col items-center gap-2 text-text-muted py-8">
        <span className="text-2xl opacity-30">▦</span>
        <p className="font-mono text-xs">Chart image unavailable</p>
        <p className="font-mono text-[10px] text-text-muted/60">{url}</p>
      </div>
    )
  }

  return (
    <img
      src={bustedUrl}
      alt="Query result chart"
      onError={() => setImgError(true)}
      style={{ maxHeight: `${height}px`, objectFit: 'contain' }}
      className="w-full p-2 rounded-b-xl"
    />
  )
}

// ─── Plotly figure builder ────────────────────────────────────────────────────

function buildFigure(rows, columns, chartType, height) {
  if (!rows.length || !columns.length) {
    return { traces: [], layout: { ...BASE_LAYOUT, height } }
  }

  const type  = (chartType || 'bar').toLowerCase()
  const xCol  = columns[0]
  const yCols = columns.length > 1 ? columns.slice(1) : [columns[0]]
  const xVals = rows.map(r => r[xCol])
  const traces = []

  if (type === 'pie') {
    traces.push({
      type: 'pie', labels: xVals,
      values: rows.map(r => Number(r[yCols[0]]) || 0),
      hole: 0.35, marker: { colors: PALETTE },
      textfont: { color: '#e8eaf6', size: 11 },
    })
  } else if (type === 'scatter') {
    yCols.forEach((col, i) => traces.push({
      type: 'scatter', mode: 'markers', name: col,
      x: xVals, y: rows.map(r => Number(r[col]) || 0),
      marker: { color: PALETTE[i % PALETTE.length], size: 8, opacity: 0.85 },
    }))
  } else if (type === 'area') {
    yCols.forEach((col, i) => traces.push({
      type: 'scatter', mode: 'lines', fill: i === 0 ? 'tozeroy' : 'tonexty',
      name: col, x: xVals, y: rows.map(r => Number(r[col]) || 0),
      line: { color: PALETTE[i % PALETTE.length], width: 2 },
      fillcolor: `${PALETTE[i % PALETTE.length]}22`,
    }))
  } else if (type === 'line') {
    yCols.forEach((col, i) => traces.push({
      type: 'scatter', mode: 'lines+markers', name: col,
      x: xVals, y: rows.map(r => Number(r[col]) || 0),
      line: { color: PALETTE[i % PALETTE.length], width: 2 },
      marker: { size: 5 },
    }))
  } else {
    // bar (default)
    yCols.forEach((col, i) => traces.push({
      type: 'bar', name: col,
      x: xVals, y: rows.map(r => Number(r[col]) || 0),
      marker: { color: PALETTE[i % PALETTE.length], opacity: 0.9 },
    }))
  }

  const layout = {
    ...BASE_LAYOUT, height,
    barmode: type === 'bar' && yCols.length > 1 ? 'group' : undefined,
  }

  return { traces, layout }
}

// ─── Sub-components ───────────────────────────────────────────────────────────

function ModeBtn({ label, active, onClick }) {
  return (
    <button
      onClick={onClick}
      className={[
        'px-2.5 py-1 rounded-md font-mono text-[10px] transition-all duration-150',
        active
          ? 'bg-accent-cyan/20 text-accent-cyan border border-accent-cyan/30'
          : 'text-text-muted hover:text-text-secondary',
      ].join(' ')}
    >
      {label}
    </button>
  )
}

function Skeleton({ height }) {
  return <div className="shimmer-bg w-full rounded-b-xl" style={{ height: `${height}px` }} />
}

function EmptyChart({ height, icon }) {
  return (
    <div className="flex flex-col items-center justify-center gap-3 text-text-muted w-full" style={{ height: `${height}px` }}>
      <span className="text-3xl opacity-20">{icon}</span>
      <p className="font-mono text-xs">Run a query to see a chart</p>
    </div>
  )
}
